### PR TITLE
fix: do not timeout when VSC debugger is attached

### LINKED ISSUE #308: [Feature] Disable timeout when tests are getting debugged
When debugging tests with Visual Studio Code, I don't want to have the test timeout to cancel my debug session.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes #308

### CODE REVIEW

File: src/util.ts [hunk 1]
```diff
@@ -56,7 +56,13 @@ export class DeadlineRunner<T> {
       this._reject(error);
   }
 
+  private _isDebuggerAttached() {
+    return process.env.NODE_OPTIONS?.includes('ms-vscode.js-debug') || /--debug|--inspect/.test(process.execArgv.join(' '));
```
Comment (dgozman) [inline src/util.ts:60]: `return !!require('inspector').url()`

File: src/util.ts [hunk 2]
```diff
@@ -56,7 +56,13 @@ export class DeadlineRunner<T> {
...
+  }
+
   setDeadline(deadline: number | undefined) {
+    if (this._isDebuggerAttached())
```
Comment (dgozman) [inline src/util.ts:64]: I think this is not the best place, since it is a utility method. I'd rather make this work similarly to passing `--timeout=0` to the command line.

File: src/util.ts (hunk 1 above)
Comment (mxschmitt) [reply src/util.ts:60]: For some reason I thought I tested it, but your solution works, which is even better, awesome.

**Review by dgozman — APPROVED** [review]
