### PR TITLE
api(reporter, breaking): remove file from onError

### LINKED ISSUE #2: [carry-over] immediately fail on the top-level parse error

### PR DESCRIPTION
**Pull request by dgozman**
We used to issue `onError` with a file before `onBegin`, when getting a syntax error or a fixture validation error while
reading one of the test files. Now, we just exit immediately instead.

If importing was successful, we start running the tests and report worker errors through `Reporter.onError()`.

Fixes #2.

### CODE REVIEW

File: src/reporter.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export interface Reporter {
   onStdErr(chunk: string | Buffer, test?: Test): void;
   onTestEnd(test: Test, result: TestResult): void;
   onTimeout(timeout: number): void;
-  onError(error: TestError, file?: string): void;
+  onError(error: TestError): void;
```
Comment (pavelfeldman) [inline src/reporter.ts:27]: This is now a breaking change

Comment (dgozman) [reply src/reporter.ts:27]: Updated the description per offline discussion. PTAL.
